### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by sampov2** [zelandiya/maui#7]
Hi,

I'm asking about the status of this project. A project that I'm involved in is testing Maui as part of search indexing and this work seems potentially very useful. However it's important to have an understanding about the status of this project as well. From what I've understood, the original developer has moved on and has no interest in continuing developing Maui. Is there another maintainer for this project or has anyone shown interest in taking it over?

PS. I have created a fork that works in Java 8 that has support for the Finnish language as well as some other improvements.

**Comment by zelandiya** [comment]
Hi! I'm still monitoring the project but I'm not maintaining or further developing it. Top Quadrant have commercialised Maui and have someone who responds to people's queries in Maui and Kea Google group, but I haven't seen any of their code added to this repo unfortunately.

**Comment by sampov2** [comment]
Thanks for your quick reply and the information. It's unfortunate there is no publicly available maintained version.

**Comment by osma** [comment]
@zelandiya Would you be interested in getting pull requests for the enhanced features (e.g. Java 8 support) @sampov2 mentioned?

**Comment by osma** [comment]
The fork now lives at https://github.com/NatLibFi/maui . Most changes are in the `master` branch. 

The Finnish support is in the `feature-voikko` branch. It depends on the [Voikko](https://voikko.puimula.org/) linguistic software package, which runs partly as native (non Java) library so may be difficult to set up, depending on your environment.
